paths:
  AFDDI_manifest: /projects/u5dp/Erik_data/AFDDI/testing/processed/manifest.jsonl
  AFDDI_dataset: /projects/u5dp/Erik_data/AFDDI/testing/raw/00
  AFDDI_output: /projects/u5dp/Erik_data/AFDDI/testing/processed