paths:
  AFDDI_manifest: /projects/u5dp/Erik_data/AFDDI/processed/manifest.jsonl
  AFDDI_dataset: /projects/u5dp/Erik_data/AFDDI/AFDB_DDI/dompdbs
  AFDDI_output: /projects/u5dp/Erik_data/AFDDI/processed
  AFDDI_split_json: /projects/u5dp/Erik_data/AFDDI/AFDB_DDI/mint_index.json

  model_checkpoint_testing:
  model_checkpoint_training: